version: "2"

services:
  wares-mongo:
    image: mongo:3.4
    container_name: "wares-mongo"
    networks:
      - wares-net
    environment:
      - MONGO_DATA_DIR=WARES-data:/data/db
    volumes:
      - WARES-data:/data/db
    ports:
      - "27017:27017"
    command: mongod --logpath=/var/log/mongodb/mongodb.log --logappend
  
  wares-node:
    image: wares-be
    container_name: "wares-node"
    networks:
      - wares-net
    build:
      context: .
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/var/app
      - /var/app/node_modules
    depends_on:
      - wares-mongo
      - wares-redis
    command:
      npm run dev

  wares-redis:
    image: redis:alpine
    networks:
      - wares-net
    ports:
      - "6379"

volumes:
  WARES-data:

networks:
  wares-net:
    driver: bridge
